Template based challenges
Cloud-CV/EvalAI pull request #2989
Opened 2020-09-07 18:57 UTC by KhalidRmb

Includes the backend and frontend for the Template based challenge creation feature.

Through this new addition, challenge hosts can use pre configured challenges and get started with minimal setup.

@RishabhJain2018 @Ram81 @deshraj

2020-09-08 11:01 UTC, Ram81 requested changes

2020-09-08 11:01 UTC, Ram81 commented on frontend_v2/src/app/components/template-challenge-create/template-challenge-create.component.ts
> +	 	'name': null,
fix indentation

2020-09-08 11:01 UTC, Ram81 commented on frontend_v2/src/app/components/template-challenge-create/template-challenge-create.component.ts
> +	constructor(
fix indentation

2020-09-08 11:01 UTC, Ram81 commented on frontend_v2/src/app/components/template-challenge-create/template-challenge-create.component.ts
> +		if (this.authService.isLoggedIn()) {
fix indentation

2020-09-08 11:01 UTC, Ram81 commented on frontend_v2/src/app/components/template-challenge-create/template-challenge-create.component.ts
> +	    	this.challengePhaseData['id'] = i+1;
change to `this.challengePhaseData['id'] = i + 1;`

2020-09-08 11:01 UTC, Ram81 commented on frontend_v2/src/app/components/template-challenge-create/template-challenge-create.component.ts
> +			//FORM_DATA.append('data', JSON.stringify(this.challengeData));
remove comment if not needed

2020-09-08 11:01 UTC, Ram81 commented on frontend_v2/src/app/components/template-challenge-create/template-challenge-create.component.ts
> +				FORM_DATA.append(key, this.challengeData[key]);
fix indentation

2020-09-08 11:01 UTC, Ram81 commented on frontend_v2/src/app/components/template-challenge-create/template-challenge-create.component.ts
> +}
add newline

2020-09-10 01:11 UTC, RishabhJain2018 requested changes

2020-09-10 01:11 UTC, RishabhJain2018 commented on settings/staging.py
> +API_HOST_URL = "https://staging-evalai.cloudcv.org"
Please remove it from here.

2020-09-10 01:11 UTC, RishabhJain2018 commented on settings/prod.py
> +API_HOST_URL = "https://evalapi.cloudcv.org"
Please remove it from here.

2020-09-10 01:11 UTC, RishabhJain2018 commented on settings/common.py
> +API_HOST_URL = ""
Can we please get it from the environment and if the environment isn't having then use the default value `http://localhost:8000`

2020-09-10 01:11 UTC, RishabhJain2018 commented on settings/dev.py
> +API_HOST_URL = "http://localhost:8000"
Please remove it from here.

2020-09-10 01:11 UTC, RishabhJain2018 commented on settings/test.py
> +API_HOST_URL = "http://localhost:8000"
Please remove it from here.

2020-09-10 16:04 UTC, Ram81 commented
@KhalidRmb can you fix the failing build

2020-09-10 16:15 UTC, KhalidRmb commented
> @KhalidRmb can you fix the failing build
@Ram81 @RishabhJain2018 
Build has passed here: https://travis-ci.org/github/Cloud-CV/EvalAI/builds/725987642
Travis is not showing the new build here

2020-09-10 16:16 UTC, RishabhJain2018 commented
I restarted the build.

2020-09-10 16:24 UTC, Ram81 commented
@KhalidRmb on local I don't see any templates listed while creation. Is that not checked in?
<img width="1440" alt="Screen Shot 2020-09-10 at 9 54 20 PM" src="https://user-images.githubusercontent.com/16323427/92762416-3360d880-f3b0-11ea-9c0a-1dc0756be06f.png">

2020-09-10 16:30 UTC, Ram81 commented
@KhalidRmb for now please add 2 challenge templates in `seed.py` for dev work.

2020-09-10 17:06 UTC, RishabhJain2018 approved these changes

2020-09-10 17:09 UTC, RishabhJain2018 commented
@KhalidRmb Please let me know when this is ready after @Ram81's comment.

2020-09-10 18:04 UTC, KhalidRmb commented
@Ram81 @RishabhJain2018 
<img width="1268" alt="Screenshot 2020-09-10 at 11 33 38 PM" src="https://user-images.githubusercontent.com/31621523/92777778-2814a980-f3be-11ea-80f6-d7c3c2d2b1ea.png">

2020-09-10 18:30 UTC, RishabhJain2018 approved these changes

2020-09-10 18:31 UTC, merged