Add instructions for submission upload using cli on Submit page
Cloud-CV/EvalAI pull request #3077
Opened 2020-11-11 15:45 UTC by Ram81

### Description

This PR adds -

- [x] Instructions to make a submission using EvalAI-CLI for large submission upload

<img width="1440" alt="Screen Shot 2020-11-11 at 9 12 26 PM" src="https://user-images.githubusercontent.com/16323427/98832514-ed34fd80-2462-11eb-9cc6-169be48299ec.png">

2020-11-11 17:36 UTC, RishabhJain2018 requested changes
Can we also add instruction to make the submission `private` while submitting using CLI for both large files and code upload challenge.

2020-11-12 06:52 UTC, Ram81 commented
<img width="1440" alt="Screen Shot 2020-11-12 at 11 56 43 AM" src="https://user-images.githubusercontent.com/16323427/98905614-b7832980-24e1-11eb-8b2e-db257c7487c2.png">
<img width="1440" alt="Screen Shot 2020-11-12 at 12 21 08 PM" src="https://user-images.githubusercontent.com/16323427/98905630-bbaf4700-24e1-11eb-882d-b33074cd1020.png">

2020-11-12 19:27 UTC, RishabhJain2018 requested changes
Can we please add what `--private` does in docker based challenge. Please add it as point 4 in submit instructions.

2020-11-14 06:31 UTC, Ram81 commented
@RishabhJain2018 
<img width="1440" alt="Screen Shot 2020-11-14 at 12 00 50 PM" src="https://user-images.githubusercontent.com/16323427/99141403-11fec000-2671-11eb-9311-53a503b67b1e.png">

2020-11-14 07:53 UTC, RishabhJain2018 requested changes

2020-11-14 07:53 UTC, RishabhJain2018 commented on frontend/src/views/web/challenge/submission.html
> +                    <li>Make private submission<br>
Can we please change it to -- Use `--private` or `--public` flag in the submission command to make the submission private or public respectively.

2020-11-14 07:53 UTC, RishabhJain2018 commented on frontend/src/views/web/challenge/submission.html
> +                        <code>$ evalai push &lt;image&gt;:&lt;tag&gt; --phase &lt;phase_name&gt; --private</code>
Please remove the command as it is already added for each phase.

2020-11-14 07:53 UTC, RishabhJain2018 commented on frontend/src/views/web/challenge/submission.html
> +                                        4. Make private submission<br>
Use --private or --public flag in the submission command to make the submission private or public respectively.

2020-11-14 07:53 UTC, RishabhJain2018 commented on frontend/src/views/web/challenge/submission.html
> +                                        <code>$ evalai challenge {{challenge.challengeId}} phase {{challenge.phaseId}} submit &lt;submission_file_path&gt; --large --private</code>
Please remove this command.

2020-11-14 09:33 UTC, Ram81 commented
@RishabhJain2018 
<img width="1440" alt="Screen Shot 2020-11-14 at 3 02 54 PM" src="https://user-images.githubusercontent.com/16323427/99144280-97429e80-268a-11eb-9e67-e23bbf35ecac.png">
<img width="1440" alt="Screen Shot 2020-11-14 at 3 03 32 PM" src="https://user-images.githubusercontent.com/16323427/99144283-9c075280-268a-11eb-8806-af1f4484cdbd.png">

2020-11-14 16:25 UTC, RishabhJain2018 approved these changes

2020-11-14 17:36 UTC, merged