Remove participant team from challenge
Cloud-CV/EvalAI pull request #3086
Opened 2020-11-28 08:33 UTC by Ram81

### Description

This PR adds -
- [x] API to remove the participant team from a challenge

2020-11-29 08:28 UTC, Ram81 commented
@RishabhJain2018 if this API is supposed to be used by us then adding checks for `user` being one of the team members won't allow us to use this API right?

2020-11-29 14:42 UTC, RishabhJain2018 requested changes

2020-11-29 14:42 UTC, RishabhJain2018 commented on apps/challenges/urls.py
> +        r"^challenge/(?P<challenge_pk>[0-9]+)/team/(?P<participant_team_pk>[0-9]+)/remove_participant_team/$",
`r"^challenge/(?P<challenge_pk>[0-9]+)/team/(?P<participant_team_pk>[0-9]+)/remove_participant_team/$"` -> `r"^challenges/(?P<challenge_pk>[0-9]+)/team/(?P<participant_team_pk>[0-9]+)/remove_participant_team/$",`

2020-11-29 14:42 UTC, RishabhJain2018 commented on apps/challenges/views.py
> +def remove_participant_team_from_challenge(
We should add this in `participants` app.

2020-11-29 17:10 UTC, RishabhJain2018 requested changes
Minor Change

2020-11-29 17:10 UTC, RishabhJain2018 commented on apps/participants/views.py
> +    API to remoev the participant team from a challenge
`remoev` -> `remove`

2020-11-30 08:32 UTC, RishabhJain2018 approved these changes

2020-11-30 17:44 UTC, merged