Fix #3155: Allow toggling on leaderboard when submission is submitted/runnning
Cloud-CV/EvalAI pull request #3160
Opened 2021-01-20 17:00 UTC by burnerlee

2021-01-20 18:30 UTC, Ram81 requested changes

2021-01-20 18:30 UTC, Ram81 commented on frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.html
> +                        element.status === 'finished' ||
@burnerlee the `Show on Leaderboard` option should be disabled only when submission status is either `cancelled` or `failed`

2021-01-21 05:36 UTC, Ram81 commented
@burnerlee can you share a gif/demo showing toggling is working when status of submission is `submitted` or `running` or `submitting`?

2021-01-25 23:46 UTC, RishabhJain2018 commented
@burnerlee Any updates on this?

2021-01-26 11:00 UTC, burnerlee commented
Yeah I'll just upload this, the latest master is giving some issues in running, I'll open an issue for this

2021-01-26 11:53 UTC, burnerlee commented
![#3155](https://user-images.githubusercontent.com/55936223/105841740-20674180-5ffb-11eb-94a4-6629c59c3e6e.gif)

2021-01-26 12:20 UTC, burnerlee commented
@Ram81

2021-01-26 13:56 UTC, Ram81 approved these changes
LGTM 👍

2021-01-26 15:33 UTC, RishabhJain2018 approved these changes

2021-01-27 19:29 UTC, merged