Add auth check in participant team GET api
Cloud-CV/EvalAI pull request #3181
Opened 2021-01-27 13:56 UTC by Ram81

### Description

This PR

- [x] Adds a check to make sure only users who are participant of the team can make `GET` api call to fetch team details

2021-01-29 03:59 UTC, RishabhJain2018 requested changes
@Ram81

2021-01-29 03:59 UTC, RishabhJain2018 commented on apps/participants/views.py
> +                "error": "You are not a authorized to change team details!"
`"You are not a authorized to change team details!"` -> `" Sorry, You are not authorized to view team details."`

2021-02-02 13:43 UTC, RishabhJain2018 commented on apps/participants/views.py
> +                "error": "You are not a authorized to change team details!"
@Ram81 Can you please update this?

2021-02-02 14:19 UTC, Ram81 commented
@RishabhJain2018 done

2021-02-04 06:36 UTC, merged