Fix #2311: Fix alignment of action buttons in cards on eval page
Cloud-CV/EvalAI pull request #3218
Opened 2021-02-04 14:35 UTC by burnerlee

2021-02-04 14:36 UTC, burnerlee commented
Screenshots before the fix:
![Screenshot from 2021-02-04 20-04-29](https://user-images.githubusercontent.com/55936223/106907617-74bda000-6724-11eb-869e-033980809518.png)
![Screenshot from 2021-02-04 20-04-38](https://user-images.githubusercontent.com/55936223/106907624-75eecd00-6724-11eb-8f1a-39fe58c142d4.png)

2021-02-04 14:36 UTC, burnerlee commented
Screenshots after the fix:
![Screenshot from 2021-02-04 20-01-59](https://user-images.githubusercontent.com/55936223/106907666-8606ac80-6724-11eb-900e-5e3b9d6fefae.png)
![Screenshot from 2021-02-04 20-02-11](https://user-images.githubusercontent.com/55936223/106907671-87d07000-6724-11eb-8c54-791bb4666bc4.png)

2021-02-04 14:42 UTC, Ram81 requested changes
@burnerlee can we also change `upload` to `Upload` and `edit` to `Edit`

2021-02-04 14:43 UTC, Ram81 commented
@burnerlee can you also share screenshots of normal resolutions i.e 100% zoom

2021-02-04 14:45 UTC, burnerlee commented
![Screenshot from 2021-02-04 20-14-58](https://user-images.githubusercontent.com/55936223/106908884-b864d980-6725-11eb-829d-019fda7f4859.png)
![Screenshot from 2021-02-04 20-15-15](https://user-images.githubusercontent.com/55936223/106908889-ba2e9d00-6725-11eb-9d0e-efd2eec96771.png)

2021-02-04 14:45 UTC, burnerlee commented
@Ram81 ^^

2021-02-04 14:46 UTC, Ram81 requested changes

2021-02-04 14:46 UTC, Ram81 commented on frontend_v2/src/app/components/challenge/challengeevaluation/challengeevaluation.component.scss
> +.ev-card-panel {
@burnerlee why are we adding new css class for `ev-card-panel`. Isn't this already present?

2021-02-04 14:46 UTC, Ram81 commented on frontend_v2/src/app/components/challenge/challengeevaluation/challengeevaluation.component.scss
> +  .ev-card-panel {
same here

2021-02-04 15:11 UTC, burnerlee commented
![Screenshot from 2021-02-04 20-39-40](https://user-images.githubusercontent.com/55936223/106912798-61f99a00-6729-11eb-9999-18e565e7d5ad.png)
![Screenshot from 2021-02-04 20-39-58](https://user-images.githubusercontent.com/55936223/106912803-63c35d80-6729-11eb-847c-9554388e147a.png)

2021-02-05 16:26 UTC, Ram81 approved these changes
LGTM

2021-02-07 19:33 UTC, RishabhJain2018 approved these changes

2021-02-08 19:26 UTC, merged