[Frontend_v2] Added option to set submission visibility on Submit page
Cloud-CV/EvalAI pull request #3229
Opened 2021-02-05 17:55 UTC by Alabhya268

Fixed issue - #3217

![visibility](https://user-images.githubusercontent.com/57143358/107070446-5da4ae00-6809-11eb-9ff4-18a9d1da9c5e.png)

Alignment and padding issue will be fixed when #3220 will be merged.

2021-02-05 17:56 UTC, Alabhya268 commented
@Ram81 @RishabhJain2018 Please review this PR , If nothing needs to be changes please merge this PR, : )

2021-02-08 12:57 UTC, Ram81 requested changes
@Alabhya268 I tried making a private submission using this PR and it didn't work. Can you please fix it.

2021-02-08 12:57 UTC, Ram81 commented on frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
> +                        id="isPublicubmission"
typo `isPublicubmission` change to `isPublicSubmission`

2021-02-08 12:57 UTC, Ram81 commented on frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
> +                        value="isPublicubmission"
we don't need value when we are using label to show the option value right? Can we remove this

2021-02-08 12:57 UTC, Ram81 commented on frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
> +                      <label for="isPublicubmission" class="radio-button-text pointer">
same typo here

2021-02-08 13:31 UTC, Alabhya268 commented on frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
> +                      <label for="isPublicubmission" class="radio-button-text pointer">
I'll fix the typos

2021-02-08 13:31 UTC, Alabhya268 commented
> @Alabhya268 I tried making a private submission using this PR and it didn't work. Can you please fix it.

Interesting, I'll try to fix it .

2021-02-23 07:47 UTC, Alabhya268 commented
@Ram81, I've now fixed the submission visibility. Please have a look at this PR again.

2021-02-24 13:25 UTC, Alabhya268 commented
@Ram81, I've now fixed the submission visibility. Please have a look at this PR again.

2021-02-26 12:19 UTC, Alabhya268 commented
@Ram81, Submission visibility is now working properly , Could you please review this PR again?

2021-03-02 17:15 UTC, Alabhya268 commented
@Ram81 , Ping for this PR.

2021-03-03 17:06 UTC, Alabhya268 commented
@Ram81 , Please review this PR again.

2021-03-04 14:31 UTC, Ram81 approved these changes
LGTM 👍

2021-03-04 15:12 UTC, merged