Add documentation for evaluation script update
Cloud-CV/EvalAI pull request #3236
Opened 2021-02-13 07:39 UTC by Ram81

### Description

Add documentation for updating the evaluation script on read the docs

2021-02-13 07:40 UTC, Ram81 commented
@RishabhJain2018 how do we test this before deploying? do we have a staging setup for rtd?

2021-02-14 15:47 UTC, RishabhJain2018 requested changes
Can we please use red bounding boxes in all the images?

2021-02-14 15:47 UTC, RishabhJain2018 commented on docs/source/edit_evaluation_script.md
> +Each challenge has an evaluation script, which evaluates the submission of participants and returns the scores which will populate the leaderboard. The logic for evaluating and judging a submission i
`Each challenge` -> `Each prediction upload challenge`

2021-02-14 15:47 UTC, RishabhJain2018 commented on docs/source/edit_evaluation_script.md
> +Each challenge has an evaluation script, which evaluates the submission of participants and returns the scores which will populate the leaderboard. The logic for evaluating and judging a submission i
`and judging`, please remove this.

2021-02-14 15:47 UTC, RishabhJain2018 commented on docs/source/edit_evaluation_script.md
> +When setting up a new challenge hosts need to test multiple versions of evaluation script on EvalAI. To test multiple versions of evaluation script host can update the evaluation script of existing c
`When setting up a new challenge` -> `When setting up a new challenge,`

2021-02-14 15:47 UTC, RishabhJain2018 commented on docs/source/edit_evaluation_script.md
> +**Tada!** you have successfully updated the evaluation script for a challenge. The evaluation workers for the challenge will be restarted automatically to pick up the latest evaluation script.
`The evaluation workers for the challenge will be restarted automatically to pick up the latest evaluation script.` -> `The evaluation workers for the challenge will be restarted automatically to pick up the latest evaluation script. Please wait for a minimum of 10 minutes for the workers to restart.`

2021-02-19 18:07 UTC, RishabhJain2018 commented
@Ram81 Can you please update this PR.

2021-02-21 16:28 UTC, RishabhJain2018 approved these changes

2021-02-21 16:44 UTC, merged