Fix 3257: add feature to send mail when host creates a new challenge
Cloud-CV/EvalAI pull request #3262
Opened 2021-02-22 13:09 UTC by burnerlee

resolves #3257 by sending a mail for remote evaluation when a new challenge is created by a host user

2021-02-22 13:18 UTC, burnerlee commented
@Ram81 ping for review

2021-02-22 16:33 UTC, Ram81 requested changes

2021-02-22 16:33 UTC, Ram81 commented on apps/challenges/models.py
> +        construct_and_send_remote_evaluation_mail(instance)
@burnerlee we should call this method from `create_challenge_using_zip` API in `views/challenges.py`. When a challenge is successfully uploaded using the API and challenge is a remote evaluation challenge then only we will send this email. You can check if a challenge is a remote_evaluation challenge using `remote_evaluation` field from challenge model

2021-02-22 20:38 UTC, burnerlee commented
@Ram81 changes made

2021-02-28 15:40 UTC, burnerlee commented
@Ram81 ping

2021-02-28 19:41 UTC, Ram81 commented
@burnerlee here is the template id `d-0e5c6256407e4f9baa5a3f51c95af435`

2021-02-28 19:43 UTC, Ram81 requested changes

2021-02-28 19:43 UTC, Ram81 commented on apps/challenges/challenge_notification_util.py
> +                     "QUEUE_NAME": challenge.queue}
@burnerlee change `QUEUE_NAME` to `CHALLENGE_QUEUE_NAME`.

2021-02-28 19:43 UTC, Ram81 commented on apps/challenges/challenge_notification_util.py
> +    template_data = {"CHALLENGE_PK": challenge.id,
@burnerlee we also need to send `CHALLENGE_NAME`, `CHALLENGE_IMAGE_URL` and `CHALLENGE_URL` to the email template

2021-02-28 19:43 UTC, Ram81 commented on apps/challenges/challenge_notification_util.py
> +def construct_and_send_remote_evaluation_mail(challenge):
Please rename to `construct_and_send_challenge_details_email`

2021-03-01 04:37 UTC, burnerlee commented
@Ram81, where do i get the url of the challenge from? There seems to be no field for this is challenge model

2021-03-02 15:31 UTC, Ram81 commented
@burnerlee see the method `construct_and_send_worker_start_mail` in `challenges/challenge_notification_util.py`. Challenge URL is not stored in models it is constructed on the fly.

2021-03-02 16:42 UTC, burnerlee commented
@Ram81 thank you for the help, made the changes

2021-03-03 09:52 UTC, Ram81 requested changes

2021-03-03 09:52 UTC, Ram81 commented on apps/challenges/aws_utils.py
> +                "maxSize": challenge_obj.max_worker_instance,
@burnerlee why are these changes part of your PR?

2021-03-03 09:52 UTC, Ram81 commented on apps/challenges/models.py
> +    worker_instance_type = models.CharField(
@burnerlee these changes should not be part of your PR. Please revert them

2021-03-03 11:51 UTC, burnerlee commented
Maybe I pulled some wrong branch into my branch and all this is messed up, closing this PR and raisinhhg another one with the required changes from a new branch

2021-03-03 11:51 UTC, closed without merging