Add code upload cluster instance config in model
Cloud-CV/EvalAI pull request #3267
Opened 2021-02-24 05:18 UTC by Ram81

### Description

This PR -

- [x] Adds changes to configure code upload cluster instance setting from challenge model fields.

2021-02-24 16:20 UTC, RishabhJain2018 requested changes

2021-02-24 16:20 UTC, RishabhJain2018 commented on apps/challenges/aws_utils.py
> +                "desiredSize": 1,
Can we please add this to the database as well?

2021-02-24 16:20 UTC, RishabhJain2018 commented on apps/challenges/aws_utils.py
> +                "minSize": 1,
Can we please add this to the database as well?

2021-02-24 16:20 UTC, RishabhJain2018 commented on apps/challenges/models.py
> +    worker_disk_size = models.IntegerField(null=True, blank=True, default=500)
Please change the default to 100.

2021-02-25 12:27 UTC, RishabhJain2018 requested changes

2021-02-25 12:27 UTC, RishabhJain2018 commented on apps/challenges/serializers.py
> +            "max_worker_instance",
Can we please add `max_worker_instance` and `desired_worker_instance` here as well.

2021-02-25 13:56 UTC, Ram81 commented
@RishabhJain2018 done

2021-02-25 14:03 UTC, RishabhJain2018 approved these changes

2021-02-27 21:42 UTC, merged