[Docs] Fix #3128: Add api documentation for download_all_submissions API
Cloud-CV/EvalAI pull request #3271
Opened 2021-02-28 20:56 UTC by afif-fahim

Fixes #3128 

After changes preview:
![image](https://user-images.githubusercontent.com/33936462/109433228-7df70f80-7a39-11eb-9327-ec5b999c25cb.png)
![image](https://user-images.githubusercontent.com/33936462/109433238-8e0eef00-7a39-11eb-8324-bc2c3565df07.png)

2021-03-02 15:27 UTC, Ram81 requested changes

2021-03-02 15:27 UTC, Ram81 commented on apps/challenges/views.py
> +            description="Challenge ID",
Change `Challenge ID` to `Challenge pk`

2021-03-02 15:27 UTC, Ram81 commented on apps/challenges/views.py
> +            description="Challenge Phase ID",
Change `Challenge Phase ID` to `Challenge phase pk`

2021-03-02 15:27 UTC, Ram81 commented on apps/challenges/views.py
> +            description="File Type",
Change `File Type` to `File type`

2021-03-02 15:27 UTC, Ram81 commented on apps/challenges/views.py
> +    API endpoint to download all the submissions for a particular challenge as a csv
@afif-fahim please complete the docstrings i.e mention Arguments and API response

2021-03-02 15:27 UTC, Ram81 commented on apps/challenges/views.py
> +            description="Challenge ID",
Change to `Challenge pk`

2021-03-02 15:27 UTC, Ram81 commented on apps/challenges/views.py
> +            description="Challenge Phase ID",
Change to `Challenge phase pk`

2021-03-02 15:27 UTC, Ram81 commented on apps/challenges/views.py
> +            description="File Type",
Change to `File type`

2021-03-02 17:40 UTC, afif-fahim commented
@Ram81 updated the PR

2021-03-04 14:10 UTC, Ram81 commented
@afif-fahim can you share updated screenshot of the docs page

2021-03-04 15:07 UTC, afif-fahim commented
@Ram81, Updated screenshot of doc:
For GET:
![image](https://user-images.githubusercontent.com/33936462/109983795-5bad0c80-7d2d-11eb-98c9-bfd16698d777.png)
For POST:
![image](https://user-images.githubusercontent.com/33936462/109983881-75e6ea80-7d2d-11eb-9b15-b31c82aa603b.png)

2021-03-04 16:46 UTC, Ram81 approved these changes

2021-03-05 04:37 UTC, merged