[Frontendv1][Backend]Filter Search Results based on Challenge Name
Cloud-CV/EvalAI pull request #3291
Opened 2021-03-07 19:52 UTC by Alabhya268

[x]Add search option on all challenges and hosted challenges page

Added Search field based on Challenge name in Frontendv1.

https://user-images.githubusercontent.com/57143358/110252687-9f617980-7fac-11eb-8590-beeb9c3f224d.mp4

@Ram81 @RishabhJain2018 , Please Look at this PR.

2021-03-07 19:56 UTC, Alabhya268 commented
@RishabhJain2018 @Ram81 , Api for filtering Challenges based on names has been added in backend with this PR, though this PR is for frontendv1, Api will be used in Frontendv2, I am working on Frontendv2 to add search feature, I will soon open PR for it.

Please review this PR.

2021-03-09 12:52 UTC, Alabhya268 commented
@Ram81 please have a look at this PR.

2021-03-09 12:55 UTC, Alabhya268 commented
Ok I will make necessary changes.

2021-03-12 06:01 UTC, Alabhya268 commented on frontend/src/js/controllers/challengeListCtrl.js
> +
ok

2021-03-12 06:01 UTC, Alabhya268 commented on frontend/src/js/controllers/challengeListCtrl.js
> +                                vm.noneUpcomingChallenge = true;
```nonoUpcomingChallenge``` variable name was pre-written should i still change it?

2021-03-12 06:01 UTC, Alabhya268 commented on frontend/src/js/controllers/challengeListCtrl.js
> +                            vm.currentList[i].isLarge = "";
I will change it to bool.

2021-03-12 06:01 UTC, Alabhya268 commented on frontend/src/js/controllers/challengeListCtrl.js
> +                        vm.noneSearchedChallenge = true;
I will changed it.

2021-03-12 06:02 UTC, Alabhya268 commented on apps/challenges/views.py
> +def get_challenges_by_title(request, challenge_title):
@Ram81 , I did not understand what you mean also is it necessary to change?

2021-03-12 06:05 UTC, Alabhya268 commented
@Ram81 , I made few changes , please clear the queries above.

2021-03-12 06:18 UTC, Alabhya268 commented
@Ram81 , Please have a look at this PR again, Also please clear queries above.

2021-03-12 12:31 UTC, Alabhya268 commented on frontend/src/js/controllers/challengeListCtrl.js
> +                            vm.currentList[i].isLarge = "";
I tried to make it boolean but test were failing.

2021-03-12 15:04 UTC, Ram81 commented on frontend/src/js/controllers/challengeListCtrl.js
> +                parameters.token = null;
@Alabhya268 ?

2021-03-12 15:05 UTC, Ram81 commented on frontend/src/js/controllers/challengeListCtrl.js
> +                            vm.currentList[i].isLarge = "";
>Is this block needed for trimming challenge name?

@Alabhya268 you didn't answer this

2021-03-12 15:06 UTC, Ram81 commented on frontend/src/js/controllers/challengeListCtrl.js
> +                                vm.noneUpcomingChallenge = true;
Let it be

2021-03-12 15:07 UTC, Ram81 requested changes
@Alabhya268 please remove the search and reset buttons. If we are adding a search bar then it should filter when query is non-empty and show all challenges when query is empty.

2021-03-14 13:10 UTC, Alabhya268 commented on frontend/src/js/controllers/challengeListCtrl.js
> +                            vm.currentList[i].isLarge = "";
@Ram81 , Yes its for triming. Also its for written like it for rendering all challenges so i did it too.

2021-03-14 13:12 UTC, Alabhya268 commented on frontend/src/js/controllers/challengeListCtrl.js
> +                parameters.token = null;
@Ram81 , Not setting token equal null has no negative effect but its was also already written for all challenges so i did it for search query too.

2021-03-14 13:14 UTC, Alabhya268 commented on apps/challenges/views.py
> +def get_challenges_by_title(request, challenge_title):
@Ram81, I am still learning django , could you please share the syntax for how it can be done as suggestion.

2021-03-14 13:15 UTC, Alabhya268 commented
> @Alabhya268 please remove the search and reset buttons. If we are adding a search bar then it should filter when query is non-empty and show all challenges when query is empty.

Sorry for late reply as I am travelling so I do not have constant access to my laptop.

I will remove buttons.

2021-03-16 04:04 UTC, Alabhya268 commented on apps/challenges/views.py
> +def get_challenges_by_title(request, challenge_title):
@burnerlee , Could you please help me with this?

2021-03-17 12:47 UTC, Alabhya268 commented on apps/challenges/views.py
> +def get_challenges_by_title(request, challenge_title):
@Ram81 , Could you please reference any document as to how it can be done ?

2021-03-17 13:04 UTC, Ram81 commented on apps/challenges/views.py
> +def get_challenges_by_title(request, challenge_title):
@Alabhya268 check any of the `POST` requests in the codebase. You can find an example in challenge submission API where we send submission details as request data parameters.

2021-03-23 20:39 UTC, Alabhya268 commented
@Ram81, I have now made title pass as query param furthermore I've removed buttons and search bar then now filter when query is non-empty and show all challenges when query is empty.

Please review following video for better understanding -

https://user-images.githubusercontent.com/57143358/112215006-dc349e00-8c45-11eb-852a-4e8f1b761ad5.mp4

Please review this PR also let me know if further changes are required.

2021-03-24 11:46 UTC, Alabhya268 commented
@Ram81, Please give feedback on this PR.

2021-04-14 05:29 UTC, Alabhya268 commented
@Ram81, I'll open a new PR for this if which search feature will be handled by frontend only. I'll close this one.

2021-04-14 05:29 UTC, closed without merging