fix #3213: remove P tags from submissions on private leaderboards
Cloud-CV/EvalAI pull request #3295
Opened 2021-03-09 11:45 UTC by burnerlee

resolves #3213

2021-03-09 11:47 UTC, burnerlee commented
![Screenshot from 2021-03-09 17-17-00](https://user-images.githubusercontent.com/55936223/110466113-4f44fd00-80fb-11eb-8b26-390f7d9dc692.png)
No P tag is shown for the private submission made because the leaderboard for John Phase is not public

2021-03-10 18:43 UTC, Ram81 requested changes
@burnerlee can you please make these changes

2021-03-10 18:43 UTC, Ram81 commented on frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts
> +   * Returns true is leaderboard is public for the selected phase
Change `Returns true is leaderboard is public for the selected phase` to `Returns true if leaderboard is public for the selected phase`

2021-03-10 18:43 UTC, Ram81 commented on frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts
> +  isLeaderboardPublic = true;
rename to `isSelectedPhaseLeaderboardPublic`

2021-03-10 18:43 UTC, Ram81 commented on frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts
> +
remove newline

2021-03-10 20:01 UTC, burnerlee commented
@Ram81 made the fixes

2021-03-12 15:09 UTC, Ram81 approved these changes
LGTM 👍

2021-03-12 23:21 UTC, RishabhJain2018 approved these changes

2021-03-14 18:47 UTC, merged