fix layout and remove animations from privacy policy page
Cloud-CV/EvalAI pull request #3357
Opened 2021-03-25 08:17 UTC by burnerlee

resolves #3344

2021-03-25 08:18 UTC, burnerlee commented
![Screenshot_2021-03-25_13-43-11](https://user-images.githubusercontent.com/55936223/112440861-cff92f80-8d70-11eb-9ca6-bd0d8b367df0.png)
![Screenshot_2021-03-25_13-43-27](https://user-images.githubusercontent.com/55936223/112440866-d1c2f300-8d70-11eb-9ae8-31dde8342b60.png)
![Screenshot_2021-03-25_13-43-38](https://user-images.githubusercontent.com/55936223/112440869-d25b8980-8d70-11eb-9536-387a111139bc.png)
![Screenshot_2021-03-25_13-43-48](https://user-images.githubusercontent.com/55936223/112440872-d25b8980-8d70-11eb-9ab6-54683c78bcf8.png)

2021-03-28 11:49 UTC, Ram81 commented
@burnerlee can you share screenshot of the page on larger screen

2021-03-28 11:54 UTC, burnerlee commented
![Screenshot_2021-03-28_17-22-55](https://user-images.githubusercontent.com/55936223/112751211-59676680-8fea-11eb-8e59-68e322c00d9c.png)
yeah sure, sorry i missed to attach this one @Ram81

2021-03-28 11:55 UTC, Ram81 requested changes
@burnerlee minor change, rest of it LGTM

2021-03-28 11:55 UTC, Ram81 commented on frontend_v2/src/app/components/privacy-policy/privacy-policy.component.scss
> +}
add newline

2021-03-28 11:59 UTC, burnerlee commented
@Ram81 made the change

2021-03-28 14:27 UTC, Ram81 approved these changes
LGTM 👍

2021-03-30 12:58 UTC, RishabhJain2018 approved these changes

2021-04-04 03:55 UTC, merged