add instructions to make submissions through cli on frontend v2
Cloud-CV/EvalAI pull request #3367
Opened 2021-03-27 21:16 UTC by burnerlee

resolves #3348

2021-03-27 21:17 UTC, burnerlee commented
@Ram81 please review

2021-03-29 07:20 UTC, Ram81 commented
@burnerlee can you share a screenshot of the submit page

2021-03-29 11:13 UTC, burnerlee commented
![#3367](https://user-images.githubusercontent.com/55936223/112828802-d3acef00-90ad-11eb-8bb7-e63b8cbacf1d.gif)

2021-03-29 11:14 UTC, burnerlee commented
@Ram81 uploaded

2021-03-30 06:40 UTC, Ram81 commented
@burnerlee can you please fix the alignment of `public` and `private` tags in the instructions
![Screen Shot 2021-03-30 at 12 09 13 PM](https://user-images.githubusercontent.com/16323427/112944744-e2001700-9150-11eb-9bd8-93d28b8a428b.png)

2021-03-31 03:12 UTC, burnerlee commented
@Ram81 this alignment issue was also there in the frontend_v1.. fixing both in this PR.

2021-03-31 03:13 UTC, burnerlee commented
![Screenshot_2021-03-31_08-42-16](https://user-images.githubusercontent.com/55936223/113085267-23e69700-91fd-11eb-99b6-9340799ea56e.png)

2021-03-31 13:55 UTC, Ram81 requested changes

2021-03-31 13:55 UTC, Ram81 commented on frontend/src/css/modules/submission.scss
> +  }
Please remove extra spaces before `}`

2021-04-01 05:44 UTC, burnerlee commented
@Ram81 removed the whitespace

2021-04-04 12:05 UTC, Ram81 approved these changes
LGTM

2021-04-04 17:15 UTC, merged