Added 400 response for invalid file type
Cloud-CV/EvalAI pull request #3371
Opened 2021-03-28 16:58 UTC by ShauryaAg

Fixes #3358

- [x] Added 400 response if a URL with unsupported file type is submitted

2021-03-30 06:43 UTC, Ram81 requested changes
@ShauryaAg can you also share a gif/screenshot of the response notification from the UI

2021-03-30 06:43 UTC, Ram81 commented on apps/jobs/views.py
> +            allowed_files = tuple(
@ShauryaAg can we rename `allowed_files` to `allowed_file_types`

2021-03-30 06:43 UTC, Ram81 commented on apps/jobs/views.py
> +                response_data = {"error": "The file type is not supported!"}
Please mention the extension of the file in the message too

2021-03-30 13:54 UTC, ShauryaAg commented
@Ram81 Sure. Here's a video.


https://user-images.githubusercontent.com/31778302/113000414-6ec8c600-918d-11eb-9e42-4392604d7836.mp4

2021-04-04 12:05 UTC, Ram81 commented
@ShauryaAg why is the error message being shown as `Something went wrong` ? can we please fix that too as part of this PR to show the correct error message.

2021-04-04 12:44 UTC, ShauryaAg commented
Sure, @Ram81.

Here's a video.

https://user-images.githubusercontent.com/31778302/113509125-816a4300-9571-11eb-9766-c564e5a765ed.mp4

2021-04-07 14:09 UTC, Ram81 requested changes
@ShauryaAg please fix the failing build

2025-03-28 14:51 UTC, RishabhJain2018 commented
Closing this since we don't want to do the changes in Frontend V2. Please open a new PR with the changes in backend and frontend only.

2025-03-28 14:51 UTC, closed without merging