Fix leaderboard polling logic
Cloud-CV/EvalAI pull request #3423
Opened 2021-05-20 14:30 UTC by gautamjajoo

There were two problems in the polling of the leaderboard.

1. There are multiple simultaneous requests while polling the leaderboard
2. When a user leaves the challenge component and visits it again the poller is started automatically (without going to leaderboard tab)

### Fixes

1. The cause of the issue was `selectPhaseSplit` was getting called twice, [1](https://github.com/Cloud-CV/EvalAI/blob/master/frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts#L307) and [2](https://github.com/Cloud-CV/EvalAI/blob/master/frontend_v2/src/app/components/utility/selectphase/selectphase.component.html#L76). 
Fixed it by making routing changes for the child component and using `selectPhaseSplit` in the parent component.

2. Added a condition for the poller to start only if the user is at specific phase split's leaderboard.

https://user-images.githubusercontent.com/24366008/118995980-31223580-b9a5-11eb-97fb-b43f91a93da7.mp4

@Ram81 @Kajol-Kumari

2021-05-21 14:51 UTC, Kajol-Kumari requested changes
Functionality wise, it looks good to me. Please do the minor requested enhancements.

2021-05-21 14:51 UTC, Kajol-Kumari commented on frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.html
> +            [phaseSelectedUrlChange]="phaseSelectedUrlChange"
Can we please rename it to `selectedPhaseSplitUrlChange`

2021-05-21 14:51 UTC, Kajol-Kumari commented on frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts
> +
please remove the extra spaces from here

2021-05-21 14:51 UTC, Kajol-Kumari commented on frontend_v2/src/app/components/utility/selectphase/selectphase.component.ts
> +  @Input() phaseSelectedUrlChange: any;
Same here. Can we please rename it to `selectedPhaseSplitUrlChange`

2021-05-21 15:01 UTC, gautamjajoo commented
@Kajol-Kumari Done the required changes!

2021-05-23 09:41 UTC, Kajol-Kumari approved these changes
LGTM 👍

2021-05-30 12:45 UTC, Ram81 approved these changes
LGTM 👍

2021-05-31 15:06 UTC, merged