Add multi metric leaderboard
Cloud-CV/EvalAI pull request #3487
Opened 2021-06-20 14:54 UTC by Ram81

### Description

- [x] Add boolean flag in challenge model to enable leaderboard for all metrics
- [x] Add leaderboard API changes to use `order_by` field to fetch the leaderboard if specified otherwise use `default_order_by`
- [x] Add frontend changes to show dropdown and generate separate URL for each metric

2021-08-03 14:03 UTC, RishabhJain2018 requested changes
@Ram81 Do you have a working gif of it?

2021-08-03 14:03 UTC, RishabhJain2018 commented on apps/challenges/serializers.py
> +        print(obj.leaderboard.schema)
Please remove the `print` statement?

2021-08-03 14:04 UTC, RishabhJain2018 requested changes

2021-08-03 14:04 UTC, RishabhJain2018 commented on apps/challenges/models.py
> +    is_multi_metric_leaderboard = models.BooleanField(default=False)
Since we have the `metadata` field in the database, I don't think we will need this field.

2021-08-04 01:59 UTC, RishabhJain2018 commented
@Ram81 Can you please resolve the conflicts here?

2021-08-07 22:51 UTC, RishabhJain2018 reviewed
LGTM :), Is there a screenshot of the UI?

2021-08-08 22:45 UTC, RishabhJain2018 commented
@Ram81

2021-08-09 05:56 UTC, Ram81 commented
![Screen Shot 2021-08-09 at 11 25 06 AM](https://user-images.githubusercontent.com/16323427/128665091-8a4fcf77-09a8-4967-b19f-ed454523acbb.png)


Here are the screenshots
![Screen Shot 2021-08-09 at 11 25 54 AM](https://user-images.githubusercontent.com/16323427/128665096-ebbf7cf3-d27d-4543-b665-33a526160f50.png)

2021-08-09 13:55 UTC, RishabhJain2018 commented
Can we please bold the entries by which it is ordered?

2021-08-17 19:07 UTC, RishabhJain2018 commented
@Ram81 Is this PR ready to merge?

2021-08-18 02:02 UTC, Ram81 commented
![Screenshot from 2021-08-17 21-58-04](https://user-images.githubusercontent.com/16323427/129824658-14f576fd-fed3-4aca-8c72-9fe6d474004e.png)

@RishabhJain2018 this PR is ready for review. Attached a screenshot that shows a leaderboard with selected order by field column being highlighted

2021-08-18 18:00 UTC, RishabhJain2018 approved these changes

2021-08-18 18:01 UTC, merged