Add test annotation to annotations section
Cloud-CV/EvalAI pull request #3504
Opened 2021-06-28 16:55 UTC by gautamjajoo

The Upload Test Annotations is moved from the `edit phase modal` to the `Test and Annotations` section.
@Ram81 @Kajol-Kumari

![Screenshot from 2021-06-28 22-20-03](https://user-images.githubusercontent.com/24366008/123674808-a82dd200-d85f-11eb-870b-057d9de15c2b.png)

2021-07-03 11:56 UTC, Kajol-Kumari requested changes
@gautamjajoo please do the following -
1. After test annotation is finished let's clear the selected phase value.
2. The text `Test Annotation` and dropdown is currently on the same row, let make it similar to `Edit phase details` i.e keep the heading `Test Annotation:` in one row and the dropdown in the next row a bit right aligned.

2021-07-03 12:03 UTC, gautamjajoo commented on frontend_v2/src/app/components/challenge/challengesettings/challengesettings.component.ts
> +  editTestAnnotation() {
Actually the service for updating the phase name is added in the phase PR, so I will wait it to be merged, then I will update this PR!

2021-07-07 15:31 UTC, Ram81 commented
@gautamjajoo can we make the options in this section look better with appropriate padding. The section looks quite bad right now. Either move all options in a separate row or add required padding between rows and columns

2021-07-07 15:37 UTC, gautamjajoo commented
@Ram81 Actually, when I will be making the tab view these things would also change, that's why I have left that part.

2021-07-11 09:39 UTC, Ram81 commented
@gautamjajoo we still have to fix the  style for this section if we want to merge it. The current style looks quite bad. Otherwise, you can open a new PR after tab view is merged.

2021-07-11 09:42 UTC, gautamjajoo commented
Okay, so we can add this and the note for test annotation part after tab view is merged.

2021-07-17 12:02 UTC, gautamjajoo commented
@Ram81 @Kajol-Kumari How does this look? Can you suggest changes, if needed?
![Screenshot from 2021-07-17 17-31-18](https://user-images.githubusercontent.com/24366008/126036214-127229e4-40f7-4b55-ae0e-058bbdae5bd1.png)

2021-07-17 16:00 UTC, Kajol-Kumari commented
> @Ram81 @Kajol-Kumari How does this look? Can you suggest changes, if needed?
> ![Screenshot from 2021-07-17 17-31-18](https://user-images.githubusercontent.com/24366008/126036214-127229e4-40f7-4b55-ae0e-058bbdae5bd1.png)

@gautamjajoo How about making the UI somewhat similar to ⬇️ 
<img width="1136" alt="Screenshot 2021-07-17 at 9 28 59 PM" src="https://user-images.githubusercontent.com/44888949/126042779-492c3f12-d3f3-49f7-a27d-48591e7ceb09.png">

2021-07-17 16:35 UTC, gautamjajoo commented
By mentioning `Annotation` as heading, I thought it would be easier for hosts to know the reason behind the selection of phase in this section. I can change it to any of the above, as you say.
@Ram81 @Kajol-Kumari

2021-07-18 15:08 UTC, Ram81 commented
@gautamjajoo it should just be 1 heading `Evaluation and Annotations`.  And we should move the test annotations section in `Edit phase details` section now. As we already have phase dropdown added there. We can put it back in the modal that pops up when we try to edit the phase details. It would be bad UX to have multiple dropdowns for phase details edit and annotations edit. Sorry about the back and forth.

2021-07-18 15:09 UTC, Ram81 commented
In that tab view of settings page we will put `Evaluation script and guidelines` under evaluation tab with worker logs and worker status UI. We won't need a separate section for annotations update it can be part of edit phase details

2021-07-18 15:11 UTC, gautamjajoo commented
So, the test annotation part would be in the edit phase detail modal, right?
So where would the note be when the file size > 100mb?

2021-07-19 16:58 UTC, gautamjajoo commented
Closing the PR since we don't need this feature now.

2021-07-19 16:58 UTC, closed without merging