[Frontend] Add Leaderboard metric order arrows
Cloud-CV/EvalAI pull request #3561
Opened 2021-08-01 19:38 UTC by Ram81

### Description

This PR adds feature 2 proposed in #3485 - 

- [x] Show "Higher is better" or "Lower is better" for each leaderboard metric
- [x]  Show metric description in a tooltip when a user hovers on it

2021-08-01 19:42 UTC, Ram81 commented
Screenshot for reference:

![Screen Shot 2021-08-02 at 1 04 41 AM](https://user-images.githubusercontent.com/16323427/127783395-feb86f05-71a6-4491-897d-6f065fbe7e6e.png)

2021-08-01 23:07 UTC, RishabhJain2018 requested changes
@Ram81 What about the models and API changes for this feature?

2021-08-01 23:07 UTC, RishabhJain2018 commented on frontend/src/css/modules/leaderboard.scss
> +}
Please add a new line here.

2021-08-02 12:49 UTC, Ram81 commented
@RishabhJain2018 we are adding metadata as part of leaderboard schema [here](https://github.com/Cloud-CV/EvalAI-Starters/pull/51) so we won't need any model and API changes. Do we want to add separate field for metadata?

2021-08-02 15:14 UTC, RishabhJain2018 commented
yeah, that works but I don't see any API changes in the PR to get that value from the config.yaml and then store it?

2021-08-02 15:14 UTC, RishabhJain2018 commented
Oh, nvm, got it.

2021-08-02 15:15 UTC, RishabhJain2018 requested changes

2021-08-02 15:15 UTC, RishabhJain2018 commented on frontend/src/js/controllers/challengeCtrl.js
> +            console.log("");
Please remove the console from here?

2021-08-02 16:24 UTC, RishabhJain2018 approved these changes

2021-08-02 16:24 UTC, merged