Added requirements file to config zip and GUI view of reqwuirements
Cloud-CV/EvalAI pull request #3593
Opened 2021-09-08 20:55 UTC by vinceli1004

2021-09-08 22:48 UTC, RishabhJain2018 requested changes
@vinceli1004 Can you please add the description for the PR mainly what this PR adds and what is the approach for it.

2021-09-08 23:10 UTC, vinceli1004 commented
> @vinceli1004 Can you please add the description for the PR mainly what this PR adds and what is the approach for it.

Added!

2021-09-08 23:26 UTC, Ram81 requested changes

2021-09-08 23:26 UTC, Ram81 commented on apps/challenges/migrations/0086_challenge_requirements.py
> +# Generated by Django 2.2.20 on 2021-08-11 06:51
@vinceli1004 we should remove this migration file as we are not making any model changes

2021-09-08 23:26 UTC, Ram81 commented on apps/challenges/migrations/0087_auto_20210811_0825.py
> +# Generated by Django 2.2.20 on 2021-08-11 08:25
same here

2021-09-08 23:26 UTC, Ram81 commented on apps/challenges/migrations/0088_auto_20210811_0833.py
> +# Generated by Django 2.2.20 on 2021-08-11 08:33
same here

2021-09-08 23:26 UTC, Ram81 commented on apps/challenges/migrations/0089_auto_20210811_0842.py
> +# Generated by Django 2.2.20 on 2021-08-11 08:42
same here

2021-09-08 23:26 UTC, Ram81 commented on apps/challenges/migrations/0090_auto_20210813_0245.py
> +# Generated by Django 2.2.20 on 2021-08-13 02:45
same here

2021-09-08 23:26 UTC, Ram81 commented on apps/challenges/migrations/0091_remove_challenge_requirements.py
> +# Generated by Django 2.2.20 on 2021-09-04 23:30
same here

2021-09-08 23:26 UTC, Ram81 commented on apps/challenges/models.py
> +
remove this newline

2021-09-08 23:26 UTC, Ram81 commented on apps/challenges/views.py
> +    except:
Please handle the exception using a exception class

2021-09-08 23:26 UTC, Ram81 commented on apps/challenges/views.py
> +    except:  # noqa: E722
same here

2021-09-08 23:26 UTC, Ram81 commented on scripts/workers/submission_worker.py
> +            print(subprocess_output)
Please remove the print statement

2021-09-15 15:59 UTC, Ram81 requested changes
@vinceli1004 can we remove the API based on our discussion.

2021-09-15 15:59 UTC, Ram81 commented on apps/challenges/urls.py
> +    url(
@vinceli1004 can we remove this API

2021-09-20 22:01 UTC, RishabhJain2018 approved these changes

2021-09-20 22:02 UTC, merged