[Frontend] Update partner organization logos
Cloud-CV/EvalAI pull request #3635
Opened 2021-12-04 20:26 UTC by Ram81

### Description

This PR - 

- [x] Updates partner organization logos on the landing page.

2021-12-07 18:40 UTC, RishabhJain2018 requested changes
The motional and other logos looks a bot bigger than other logos. Can we please make them a bit smaller.

2021-12-07 21:27 UTC, Ram81 commented
Fixed it
![Screenshot from 2021-12-07 16-26-58](https://user-images.githubusercontent.com/16323427/145108669-81767125-7136-4566-a8d0-c66c3afcddce.png)

2021-12-08 18:29 UTC, Ram81 commented
@RishabhJain2018 can we merge this?

2021-12-20 01:00 UTC, RishabhJain2018 approved these changes

2021-12-20 01:01 UTC, merged