[FrontendV2] Add UI support for submission meta attributes
Cloud-CV/EvalAI pull request #3648
Opened 2021-12-20 00:20 UTC by Ram81

### Description

This PR - 

- [x] Adds support for submission meta attributes on submit page in Frontend V2

2021-12-28 00:59 UTC, RishabhJain2018 requested changes
@Ram81 Minor change.

2021-12-28 19:57 UTC, Ram81 commented
@RishabhJain2018 I don't see the comment for the change. Can you comment it again?

2021-12-29 01:38 UTC, RishabhJain2018 requested changes

2021-12-29 01:38 UTC, RishabhJain2018 commented on frontend_v2/src/app/services/global.service.ts
> +      console.log(item.label + " -- " + label + " ---- " + item.value);
Please remove the console statement.

2021-12-29 20:37 UTC, RishabhJain2018 commented
@Ram81 Please resolve the conflicts here.

2021-12-29 20:59 UTC, RishabhJain2018 approved these changes

2021-12-29 20:59 UTC, merged