Allow only downscaling for past challenge workers
Cloud-CV/EvalAI pull request #3813
Opened 2022-09-29 23:48 UTC by gchhablani

This PR modifies the auto-scaling script in order to only allow downscaling for the past challenge workers.

2022-10-02 21:54 UTC, Ram81 requested changes
rest of the PR looks good. Minor comments

2022-10-02 21:54 UTC, Ram81 commented on scripts/monitoring/auto_scale_workers.py
> +        decrease_workers(challenge, num_workers)
can you rename the method to `scale_down_workers`?

2022-10-02 21:54 UTC, Ram81 commented on scripts/monitoring/auto_scale_workers.py
> +        increase_workers(challenge, num_workers)
can you rename the method to `scale_up_workers`?

2022-10-02 21:54 UTC, Ram81 commented on scripts/monitoring/auto_scale_workers.py
> +from datetime import datetime
Can we have all the imports starting with `from` after the `import <package>` statements?

2022-10-03 16:51 UTC, gchhablani commented
@Ram81 I have changed `increase_or_decrease` to `scale_up_or_down` as well. Hope that's okay.

2022-10-13 03:55 UTC, Ram81 approved these changes

2022-10-13 03:55 UTC, merged