Fetch last 10 event logs from the last 72 hours
Cloud-CV/EvalAI pull request #3832
Opened 2022-11-12 21:26 UTC by gchhablani

This PR attempts to address the issue of losing the logs beyond last 15 minutes. Here, we try to fetch the logs for the last 10 events in the past 72 hours.

Please let me know what you think.

@Ram81

2022-12-05 03:11 UTC, Ram81 requested changes

2022-12-05 03:11 UTC, Ram81 commented on apps/challenges/views.py
> +    timeframe = 4320  # 15
Can you remove the comments `# 15` and `# logs last 1000 lines`?

2022-12-06 00:59 UTC, gchhablani commented
Added the change from review.

2022-12-06 22:16 UTC, Ram81 approved these changes

2022-12-06 22:16 UTC, merged