[Logging] Expose Environment Logs to Challenge Hosts
Cloud-CV/EvalAI pull request #3879
Opened 2023-03-08 23:41 UTC by gchhablani

This PR exposes environment logs from AWS to challenge hosts for code upload challenges as a PR.
This PR is based on @matthew-so's PR #3809.

2023-03-18 01:37 UTC, Ram81 requested changes

2023-03-18 01:37 UTC, Ram81 commented on apps/jobs/models.py
> +    )
can we rename this to `environment_log_file`

2023-03-19 00:02 UTC, Ram81 requested changes

2023-03-19 00:02 UTC, Ram81 commented on apps/jobs/models.py
> +        upload_to=RandomFileName("submission_files/submission_{id}"),
Can you change the path of the file here? This should be `submission_files/environment_log_file_{id}`

2023-03-19 00:17 UTC, gchhablani commented
Added the changes

2023-03-19 01:08 UTC, Ram81 approved these changes

2023-03-19 01:08 UTC, merged